name: Nuclei - Vulnerability Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nuclei and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          curl -sL https://install.projectdiscovery.io | bash

      - name: Run Nuclei scan and save JSON
        run: |
          nuclei -target https://animated-space-broccoli-pp64rwg4g7436w9j-3000.app.github.dev/ -json > nuclei.json

      - name: Convert JSON to SARIF
        run: |
          curl -L -o nuclei-to-sarif https://github.com/juice-shop/nuclei-to-sarif/releases/latest/download/nuclei-to-sarif-linux
          chmod +x nuclei-to-sarif
          ./nuclei-to-sarif -input nuclei.json -output nuclei.sarif

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nuclei.sarif
